-- Criar a tabela de banco de questões
CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blue_text text NOT NULL,
  yellow_question text NOT NULL,
  yellow_options jsonb NOT NULL,
  yellow_correct_index integer NOT NULL,
  red_text text NOT NULL,
  red_options jsonb NOT NULL,
  red_correct_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar acesso público ao banco de questões
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon all on questions" ON public.questions FOR ALL USING (true);

-- Adicionar o controle de pergunta atual no jogo
ALTER TABLE public.games ADD COLUMN current_question_id bigint REFERENCES public.questions(id);

-- Inserir uma pergunta de teste inicial para garantir que o jogo não fique vazio
INSERT INTO public.questions (blue_text, yellow_question, yellow_options, yellow_correct_index, red_text, red_options, red_correct_index)
VALUES (
  'Paciente de 45 anos dá entrada no PS com dor torácica irradiada para o braço esquerdo e sudorese fria.',
  'Qual é a primeira conduta recomendada perante este quadro?',
  '["A) Solicitar ECG em até 10 minutos", "B) Dar alta com analgésico", "C) Solicitar Raio-X de Tórax apenas", "D) Aguardar exames de sangue"]'::jsonb,
  0,
  'O paciente apresentou PCR (Parada Cardiorrespiratória)!',
  '["A) Iniciar RCP e Desfibrilação", "B) Chamar a família", "C) Mudar de leito de enfermaria", "D) Preencher prontuário primeiro"]'::jsonb,
  0
);

-- Atualizar o jogo padrão para apontar para a pergunta 1
UPDATE public.games SET current_question_id = (SELECT id FROM public.questions LIMIT 1) WHERE id = '11111111-1111-1111-1111-111111111111';
