-- Criar tabela de games (Salas)
CREATE TABLE public.games (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  phase text NOT NULL DEFAULT 'DICE', -- Fases: 'DICE', 'BLUE_CARD', 'YELLOW_CARD', 'RED_CARD'
  active_player_id bigint,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Criar tabela de players
CREATE TABLE public.players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id uuid REFERENCES public.games(id) ON DELETE CASCADE,
  name text NOT NULL,
  avatar text NOT NULL,
  position integer DEFAULT 0,
  lives integer DEFAULT 3,
  wildcard_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar o Supabase Realtime (WebSockets) para as tabelas
alter publication supabase_realtime add table public.games;
alter publication supabase_realtime add table public.players;

-- Habilitar RLS (Row Level Security) e permitir acesso público anônimo para o protótipo
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon all on games" ON public.games FOR ALL USING (true);
CREATE POLICY "Allow anon all on players" ON public.players FOR ALL USING (true);

-- ==========================================
-- DADOS INICIAIS (SEED)
-- Inserir a primeira sala (ID Fixo para facilitar o protótipo)
-- ==========================================
INSERT INTO public.games (id, phase) 
VALUES ('11111111-1111-1111-1111-111111111111', 'DICE');

-- Inserir 3 jogadores mockados vinculados a esta sala
INSERT INTO public.players (game_id, name, avatar) VALUES
('11111111-1111-1111-1111-111111111111', 'Dr. Lucas', 'https://i.pravatar.cc/150?u=lucas'),
('11111111-1111-1111-1111-111111111111', 'Dra. Amanda', 'https://i.pravatar.cc/150?u=amanda'),
('11111111-1111-1111-1111-111111111111', 'Dr. Roberto', 'https://i.pravatar.cc/150?u=roberto');
